services:
  postgres:
    image: postgres:17
    container_name: pipelinehub_postgres

    environment:
      POSTGRES_DB: pipelinehub
      POSTGRES_USER: pipelinehub
      POSTGRES_PASSWORD: pipelinehub

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: