"""add config to data sources

Revision ID: 7bd52906a4e3
Revises: 89805f6bf041
Create Date: 2026-09-16 18:58:42.291668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bd52906a4e3'
down_revision: Union[str, Sequence[str], None] = '89805f6bf041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'config')
    # ### end Alembic commands ###
